package unit_test

import (
	"encoding/json"
	"testing"
)

// TestPKIRolesStructure verifies the PKI roles JSON structure
func TestPKIRolesStructure(t *testing.T) {
	// Example PKI roles as generated by createPKIRoles()
	rolesJSON := `{
		"device-base": {
			"allowed_domains": ["example.com"],
			"allow_subdomains": true,
			"max_ttl": "8760h",
			"organization": ["Kontango"],
			"country": ["US"],
			"description": "Base device identity (1 year, external resolvable)"
		},
		"device-web": {
			"allowed_domains": ["web.example.com"],
			"allow_subdomains": true,
			"max_ttl": "24h",
			"organization": ["Kontango"],
			"country": ["US"],
			"description": "Web testing (24h, quarantine devices, internal Ziti DNS)"
		},
		"device-lab": {
			"allowed_domains": ["lab.example.com"],
			"allow_subdomains": true,
			"max_ttl": "8760h",
			"organization": ["Kontango"],
			"country": ["US"],
			"description": "Public internal services (1yr, resolvable via Ziti DNS)"
		},
		"device-tango": {
			"allowed_domains": ["tango"],
			"allow_subdomains": true,
			"max_ttl": "8760h",
			"organization": ["Kontango"],
			"country": ["US"],
			"description": "Production devices (1yr, unresolvable, Ziti DNS only)"
		}
	}`

	var roles map[string]interface{}
	if err := json.Unmarshal([]byte(rolesJSON), &roles); err != nil {
		t.Fatalf("Failed to parse roles JSON: %v", err)
	}

	// Expected roles
	expectedRoles := []string{"device-base", "device-web", "device-lab", "device-tango"}

	// Verify all expected roles exist
	for _, roleName := range expectedRoles {
		if _, ok := roles[roleName]; !ok {
			t.Errorf("Missing role: %s", roleName)
		}
	}

	// Verify structure of each role
	for roleName, roleData := range roles {
		role, ok := roleData.(map[string]interface{})
		if !ok {
			t.Errorf("Role %s is not a map", roleName)
			continue
		}

		// Verify required fields
		if _, ok := role["allowed_domains"]; !ok {
			t.Errorf("Role %s missing allowed_domains", roleName)
		}
		if _, ok := role["allow_subdomains"]; !ok {
			t.Errorf("Role %s missing allow_subdomains", roleName)
		}
		if _, ok := role["max_ttl"]; !ok {
			t.Errorf("Role %s missing max_ttl", roleName)
		}
		if _, ok := role["organization"]; !ok {
			t.Errorf("Role %s missing organization", roleName)
		}
		if _, ok := role["country"]; !ok {
			t.Errorf("Role %s missing country", roleName)
		}
		if _, ok := role["description"]; !ok {
			t.Errorf("Role %s missing description", roleName)
		}
	}
}

// TestPKIRolesDomainConfiguration verifies domain configuration per role
func TestPKIRolesDomainConfiguration(t *testing.T) {
	tests := []struct {
		roleName              string
		expectedDomain        string
		shouldHaveDomainSuffix bool
	}{
		{"device-base", "example.com", true},
		{"device-web", "web.example.com", true},
		{"device-lab", "lab.example.com", true},
		{"device-tango", "tango", false}, // No domain suffix - unresolvable
	}

	for _, tt := range tests {
		t.Run(tt.roleName, func(t *testing.T) {
			// Verify domain configuration
			hasDomainSuffix := hasDomainSuffix(tt.expectedDomain)
			if hasDomainSuffix != tt.shouldHaveDomainSuffix {
				t.Errorf("Domain %s: hasSuffix=%v, want %v",
					tt.expectedDomain, hasDomainSuffix, tt.shouldHaveDomainSuffix)
			}
		})
	}
}

// TestPKIRolesTTL verifies TTL configuration per role
func TestPKIRolesTTL(t *testing.T) {
	tests := []struct {
		roleName    string
		expectedTTL string
	}{
		{"device-base", "8760h"},  // 1 year
		{"device-web", "24h"},     // 1 day (short-lived)
		{"device-lab", "8760h"},   // 1 year
		{"device-tango", "8760h"}, // 1 year
	}

	for _, tt := range tests {
		t.Run(tt.roleName, func(t *testing.T) {
			// Just verify TTL values are reasonable
			if tt.expectedTTL == "" {
				t.Error("TTL not set")
			}
			// Verify it ends with 'h' for hours
			if len(tt.expectedTTL) < 2 || tt.expectedTTL[len(tt.expectedTTL)-1] != 'h' {
				t.Errorf("Invalid TTL format: %s", tt.expectedTTL)
			}
		})
	}
}

// TestPKIRolesHierarchy verifies the role hierarchy
func TestPKIRolesHierarchy(t *testing.T) {
	// Role hierarchy by access level
	hierarchy := []struct {
		level   int
		role    string
		purpose string
	}{
		{0, "device-base", "All devices - external public"},
		{1, "device-web", "Quarantine testing - short-lived"},
		{2, "device-lab", "Approved devices - Bao access"},
		{3, "device-tango", "Admin-only - experimental/hidden"},
	}

	for i, h := range hierarchy {
		t.Run(h.role, func(t *testing.T) {
			if h.level < 0 || h.level > 3 {
				t.Errorf("Invalid level: %d", h.level)
			}
			if h.role == "" {
				t.Error("Role name not set")
			}
			if h.purpose == "" {
				t.Error("Purpose not set")
			}
			_ = i
		})
	}
}

// Helper function to check if a domain has a suffix
func hasDomainSuffix(domain string) bool {
	// Simple check: if it contains a dot, it has a suffix
	for _, ch := range domain {
		if ch == '.' {
			return true
		}
	}
	return false
}
